2019-01-05 21:28:44,074 ERROR: Exception on /users/updatepassword [GET] [in c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Rohit\DEV\ShopNow\app\users\routes.py", line 34, in updatePassword
    return(render_template('updatepassword.html', title='Update User Details', form=form))
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\rohit\envs\shopnow\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Rohit\DEV\ShopNow\app\users\templates\updatepassword.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "C:\Users\Rohit\DEV\ShopNow\app\templates\base.html", line 42, in top-level template code
    {% block content %}
  File "C:\Users\Rohit\DEV\ShopNow\app\users\templates\updatepassword.html", line 8, in block "content"
    {{form.username.label}}
  File "c:\users\rohit\envs\shopnow\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.users.forms.UpdatePasswordForm object' has no attribute 'username'
